### ISSUE TITLE
error compiling/linking latest firmware 1.29.3

### ISSUE THREAD

**Issue by arohrbacher** [schodet/nxt-firmware#1]
Hi,
I am trying to compile the latest firmware under Linux, using the prebuilt toolchain referenced in
https://nxt-firmware.ni.fr.eu.org/step_by_step/linux/
(https://sourcery.mentor.com/sgpp/lite/arm/portal/package6493/public/arm-none-eabi/arm-2010q1-188-arm-none-eabi-i686-pc-linux-gnu.tar.bz2)
I cloned the github repository, changed into the repo and issued "make".
The compilation goes OK, but there is a linker error at the end:
/home/andreas/Desktop/arm-2010q1/bin/../lib/gcc/arm-none-eabi/4.4.1/../../../../arm-none-eabi/bin/ld: cannot find -lnosys
collect2: ld returned 1 exit status
make: *** [nxt_firmware.elf] Error 1

After googling a bit, it seems that libnosys.a is missing - I didn't find this file anywhere in the toolchain.
What am I doing wrong?

Thanks, Andreas

**Comment by schodet** [comment]
Hi,

I added -lnosys recently for recent toolchains, you can try to use a more recent toolchain or remove the -lnosys flag in Makefile.

I need to refresh the documentation page.

**Comment by arohrbacher** [comment]
Hi,
thanks for the quick reply. Indeed removing the -lnosys from the Makefile produces a firmware file, i.e. the linker error is gone. Is this then OK, i.e. will there be no instabilities or such when running the firmware?
I am willing to try a newer toolchain - could you give a suitable link? The sourcery page referenced in https://nxt-firmware.ni.fr.eu.org/build/gcc/install/
(https://sourcery.sw.siemens.com/sgpp/lite/arm/portal/subscription?@template=lite) is a little confusing for me - I don't know which of the many toolchains they list to use...

Best regards,

Andreas

**Comment by schodet** [comment]
You can get a recent toolchain from ARM directly here : https://developer.arm.com/downloads/-/gnu-rm

For linux, assuming you have a regular PC, you need `gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2`

There is no instabilities to be afraid of if it build, but of course I can not give guaranties it will work.

I personally use the arm toolchain which come with my distribution ( gcc-arm-none-eabi package on debian), I can give a try with the one linked above this evening if you want to be sure :)

I will update the page on nxt-firmware, but it will not be done today.

**Comment by arohrbacher** [comment]
Hi again,

I am indeed on a "regular" Linux-PC (actually a Ubuntu 14.04 64bit VM under Windows :-) - this just because I am now too lazy to setup a newer Ubuntu distro).
Cool, `gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2` works and built a firmware file (with the original Makefile) - many thanks for your pointers and help!
Also thanks for confirming that there are no expected "instabilities" when I compile without the -lnosys flag...

Best, Andreas

**Comment by schodet** [comment]
Old VM for an old LEGO brick, seems perfectly fine :)

Have fun!
